/* Descriptive Questions - Motion | CBSE Grade 9 */
window.descriptiveData = [
  { question: "Distinguish between distance and displacement.", answer: "<strong>Distance</strong> is the total path length covered by an object — a scalar quantity that is always positive. <strong>Displacement</strong> is the shortest distance between the initial and final positions, along with direction — a vector quantity. Distance is always greater than or equal to the magnitude of displacement.", marks: 2 },
  { question: "Can an object have zero displacement but non-zero distance? Give an example.", answer: "Yes. When an object returns to its exact starting point after travelling along some path (e.g., one complete round of a circular track), the displacement is zero (initial and final positions coincide) but the distance covered equals the length of the path travelled, which is non-zero.", marks: 2 },
  { question: "Define uniform and non-uniform motion with one example each.", answer: "<strong>Uniform motion:</strong> An object covers equal distances in equal intervals of time, however small the intervals may be. Example: a car moving at a constant 60 km/h on a straight highway.<br><strong>Non-uniform motion:</strong> An object covers unequal distances in equal intervals of time. Example: a car in city traffic, speeding up and slowing down.", marks: 2 },
  { question: "What is the difference between speed and velocity?", answer: "<strong>Speed</strong> is the distance travelled per unit time; it is a scalar quantity with only magnitude, always positive.<br><strong>Velocity</strong> is the displacement per unit time; it is a vector quantity with both magnitude and direction, and can be positive, negative, or zero. Two objects can have the same speed but different velocities if they move in different directions.", marks: 3 },
  { question: "Derive the equation of motion v = u + at using a velocity-time graph.", answer: "Consider a velocity–time graph where an object's velocity changes uniformly from u (at t=0) to v (at time t). The graph is a straight line from point A (0, u) to point B (t, v).<br><br>Acceleration = slope of the line = (v − u) / (t − 0)<br>⟹ a = (v − u) / t<br>⟹ at = v − u<br>⟹ <strong>v = u + at</strong><br><br>This is the first equation of motion, giving velocity at any time t under uniform acceleration.", marks: 3 },
  { question: "Derive s = ut + ½at² using a velocity-time graph.", answer: "In the velocity-time graph, displacement s equals the area under the graph between t=0 and time t.<br><br>This area is a trapezium, split into a rectangle (area = ut) and a triangle (area = ½ × t × (v−u)).<br><br>Since v − u = at (from first equation):<br>s = ut + ½ × t × at<br>⟹ <strong>s = ut + ½at²</strong><br><br>This is the second equation of motion, giving displacement at any time t.", marks: 3 },
  { question: "A car accelerates uniformly from 18 km/h to 36 km/h in 5 seconds. Calculate the acceleration and the distance covered.", answer: "<strong>Given:</strong> u = 18 km/h = 5 m/s, v = 36 km/h = 10 m/s, t = 5 s<br><br><strong>Acceleration:</strong> a = (v−u)/t = (10−5)/5 = <strong>1 m/s²</strong><br><br><strong>Distance:</strong> s = ut + ½at² = (5×5) + ½×1×5² = 25 + 12.5 = <strong>37.5 m</strong>", marks: 3, type: "case" },
  { question: "A ball is gently dropped from a height of 20 m. If its velocity increases uniformly at the rate of 10 m/s² due to gravity, with what velocity will it strike the ground? After what time will it strike the ground?", answer: "<strong>Given:</strong> u = 0 (dropped from rest), s = 20 m, a = 10 m/s²<br><br><strong>Using v² = u² + 2as:</strong><br>v² = 0 + 2×10×20 = 400<br>v = <strong>20 m/s</strong><br><br><strong>Using v = u + at:</strong><br>20 = 0 + 10t<br>t = <strong>2 seconds</strong>", marks: 3, type: "case" },
  { question: "An athlete completes one round of a circular track of diameter 200 m in 40 seconds. What will be the distance covered and displacement at the end of 2 minutes 20 seconds?", answer: "<strong>Circumference</strong> = πd = π×200 ≈ 628 m. Time for 1 round = 40 s.<br><br>In 2 min 20 s = 140 s, number of rounds = 140/40 = 3.5 rounds.<br><br><strong>Distance covered</strong> = 3.5 × 628 = <strong>2198 m</strong><br><br>After 3.5 rounds, the athlete is at the diametrically opposite point of the track from the start.<br><strong>Displacement</strong> = diameter = <strong>200 m</strong> (directed toward the opposite end of the track)", marks: 3, type: "case" },
  { question: "Explain why uniform circular motion is considered an accelerated motion even though the speed remains constant.", answer: "In uniform circular motion, the magnitude of velocity (speed) stays constant, but the <strong>direction</strong> of velocity keeps changing continuously as the object moves around the circle. Since velocity is a vector (with both magnitude and direction) and acceleration is defined as the rate of change of velocity, a continuous change in direction means the velocity is changing — and therefore the object is accelerating, even though its speed never changes. This acceleration is directed towards the centre of the circle.", marks: 3 }
];
